### ISSUE TITLE
Adding new acronyms

### ISSUE THREAD

**Issue by roshni-b** [nasa/NASA-Acronyms#4]
Just an idea, could there be a google form where people can suggest new acronyms to be added to your acronyms.json database. Or there could be a link to the script on nasaacronyms.com which people can modify and PR?

**Comment by joelmalissa** [comment]
I'm resuming work on this project again.  @roshni-b, this was an excellent idea.  The link to the Google Form can now be found at the bottom of the list of results.

![image](https://user-images.githubusercontent.com/44816276/109908165-c4cf4a00-7c71-11eb-80ad-a08815de5e6a.png)

There can't be a link to the script until I fully split out an internal and external version of the code.  Currently, the script takes public lists and internal lists approved for public use and syncs them daily to: https://github.com/nasa/NASA-Acronyms/blob/master/lists/.

**Comment by Samad999777** [comment]
@joelmalissa If your looking to work on the script, I would want to help you with it. Ping me if you're interested.
